name: Node.js Pipeline
run-name: Pipeline started by ${{ github.actor }}
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' #improve setting this value from package.json file
          cache: 'npm'

      - name: Install Node.js Dependencies
        run:  npm install
      
      - name: Unit Tests
        run:  npm run test:unit

      - name: Integration Tests
        run: npm run test:integration

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Git Hub Registry Container
        run: docker login --username silva-welder --password ${{ secrets.GHRC_TOKEN }} ghcr.io #search ways to improve security by using SA (service account) and pass value from variable or find a fashion way to do this

      - name: Extract Repository and Application Name
        shell: bash
        run: |
          echo "APP_NAME=$(echo $GH_ACTION_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo $GH_ACTION_REPOSITORY)" >> $GITHUB_ENV
        env:
          GH_ACTION_REPOSITORY: ${{ github.action_repository || github.repository }}

      - name: Build  Docker Image
        run: |
          docker build -t ghcr.io/${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}'
          output: trivy-report.sarif
          format: sarif
          #exit-code: '1' #activate this if you want to generate error when find a vulnerability
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Test
        run:  ls -al && cat trivy-report.sarif
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}